"""
Script to add library due date reminders to Google Calendar using the JSON file
generated by webscrape.py

Prerequisites:
1. Install Google API client: pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib
2. Set up Google Calendar API credentials:
   - Go to https://console.cloud.google.com/
   - Create a project and enable Calendar API
   - Create OAuth 2.0 credentials
   - Download credentials.json to this directory
3. Run this script: python add_to_calendar.py
"""

import json
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
import os.path

# If modifying these scopes, delete the file token.json.
SCOPES = ['https://www.googleapis.com/auth/calendar']

def authenticate_google_calendar():
    """Authenticate and return Google Calendar service"""
    creds = None
    # The file token.json stores the user's access and refresh tokens.
    if os.path.exists('token.json'):
        creds = Credentials.from_authorized_user_file('token.json', SCOPES)
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            if not os.path.exists('credentials.json'):
                print("Error: credentials.json not found!")
                print("Please download your OAuth 2.0 credentials from Google Cloud Console")
                return None
            flow = InstalledAppFlow.from_client_secrets_file(
                'credentials.json', SCOPES)
            creds = flow.run_local_server(port=0)
        # Save the credentials for the next run
        with open('token.json', 'w') as token:
            token.write(creds.to_json())
    
    try:
        service = build('calendar', 'v3', credentials=creds)
        return service
    except HttpError as error:
        print(f'An error occurred: {error}')
        return None

def add_events_to_calendar(service, events_data):
    """Add events from JSON file to Google Calendar"""
    if not service:
        print("Calendar service not available")
        return
    
    events = events_data.get('events', [])
    print(f"Adding {len(events)} events to Google Calendar...")
    
    added_count = 0
    failed_count = 0
    
    for event in events:
        try:
            # Create the event
            created_event = service.events().insert(
                calendarId='primary',
                body=event
            ).execute()
            
            print(f"✓ Added: {event['summary']} (Due: {event['start']['dateTime']})")
            added_count += 1
            
        except HttpError as error:
            print(f"✗ Failed to add {event['summary']}: {error}")
            failed_count += 1
    
    print(f"\n{'='*60}")
    print(f"Summary: {added_count} events added, {failed_count} failed")
    print(f"{'='*60}")

def main():
    # Load the JSON file generated by webscrape.py
    json_filename = "library_due_dates.json"
    
    if not os.path.exists(json_filename):
        print(f"Error: {json_filename} not found!")
        print("Please run webscrape.py first to generate the calendar events.")
        return
    
    # Load events from JSON
    with open(json_filename, 'r', encoding='utf-8') as f:
        events_data = json.load(f)
    
    print(f"Loaded {len(events_data.get('events', []))} events from {json_filename}")
    
    # Authenticate and get calendar service
    service = authenticate_google_calendar()
    
    if service:
        # Add events to calendar
        add_events_to_calendar(service, events_data)
    else:
        print("Failed to authenticate with Google Calendar")

if __name__ == '__main__':
    main()

