"""
Script to add library due date reminders to Google Calendar using the JSON file
generated by dataa.py

Prerequisites:
1. Install Google API client: pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib
2. Set up Google Calendar API credentials:
   - Go to https://console.cloud.google.com/
   - Create a project and enable Calendar API
   - Create OAuth 2.0 credentials
   - Download credentials.json to the scrapeki directory
3. Run this script: python add_to_google_calendar.py
"""

import json
import os
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

# If modifying these scopes, delete the file token.json.
SCOPES = ['https://www.googleapis.com/auth/calendar']

def authenticate_google_calendar():
    """Authenticate and return Google Calendar service"""
    creds = None
    script_dir = os.path.dirname(os.path.abspath(__file__))
    token_path = os.path.join(script_dir, 'token.json')
    credentials_path = os.path.join(script_dir, 'credentials.json')
    
    # The file token.json stores the user's access and refresh tokens.
    if os.path.exists(token_path):
        creds = Credentials.from_authorized_user_file(token_path, SCOPES)
    
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            if not os.path.exists(credentials_path):
                print("=" * 60)
                print("ERROR: credentials.json not found!")
                print("=" * 60)
                print("Please download your OAuth 2.0 credentials from Google Cloud Console:")
                print("1. Go to https://console.cloud.google.com/")
                print("2. Create a project and enable Calendar API")
                print("3. Create OAuth 2.0 credentials (Desktop app)")
                print("4. Download credentials.json to this directory:")
                print(f"   {script_dir}")
                print("=" * 60)
                return None
            
            flow = InstalledAppFlow.from_client_secrets_file(
                credentials_path, SCOPES)
            creds = flow.run_local_server(port=0)
        
        # Save the credentials for the next run
        with open(token_path, 'w') as token:
            token.write(creds.to_json())
    
    try:
        service = build('calendar', 'v3', credentials=creds)
        return service
    except HttpError as error:
        print(f'An error occurred: {error}')
        return None

def add_events_to_calendar(service, events_data):
    """Add events from JSON file to Google Calendar"""
    if not service:
        print("Calendar service not available")
        return
    
    events = events_data.get('events', [])
    if not events:
        print("No events found in the data file.")
        return
    
    print(f"\n{'=' * 60}")
    print(f"Adding {len(events)} events to Google Calendar...")
    print(f"{'=' * 60}\n")
    
    added_count = 0
    failed_count = 0
    skipped_count = 0
    
    for i, event in enumerate(events, 1):
        try:
            # Check if event already exists (optional - you can skip this if you want duplicates)
            # For now, we'll just add all events
            
            # Create the event
            created_event = service.events().insert(
                calendarId='primary',
                body=event
            ).execute()
            
            event_summary = event.get('summary', 'Unknown')
            event_date = event.get('start', {}).get('dateTime', 'Unknown')
            
            print(f"✓ [{i}/{len(events)}] Added: {event_summary}")
            print(f"  Due: {event_date}")
            print(f"  Event ID: {created_event.get('id', 'N/A')}")
            print()
            
            added_count += 1
            
        except HttpError as error:
            event_summary = event.get('summary', 'Unknown')
            print(f"✗ [{i}/{len(events)}] Failed to add: {event_summary}")
            print(f"  Error: {error}")
            print()
            failed_count += 1
        except Exception as e:
            event_summary = event.get('summary', 'Unknown')
            print(f"✗ [{i}/{len(events)}] Error adding: {event_summary}")
            print(f"  Error: {e}")
            print()
            failed_count += 1
    
    # Summary
    print("=" * 60)
    print("SUMMARY")
    print("=" * 60)
    print(f"Total events processed: {len(events)}")
    print(f"✓ Successfully added: {added_count}")
    print(f"✗ Failed: {failed_count}")
    if skipped_count > 0:
        print(f"⊘ Skipped: {skipped_count}")
    print("=" * 60)
    
    return added_count, failed_count

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    json_filename = os.path.join(script_dir, "library_due_dates.json")
    
    # Check if JSON file exists
    if not os.path.exists(json_filename):
        print("=" * 60)
        print("ERROR: library_due_dates.json not found!")
        print("=" * 60)
        print("Please run dataa.py first to generate the calendar events.")
        print(f"Expected file location: {json_filename}")
        print("=" * 60)
        return
    
    # Load events from JSON
    print("=" * 60)
    print("Google Calendar Integration")
    print("=" * 60)
    print(f"Loading events from: {json_filename}")
    
    try:
        with open(json_filename, 'r', encoding='utf-8') as f:
            events_data = json.load(f)
    except Exception as e:
        print(f"Error reading JSON file: {e}")
        return
    
    events = events_data.get('events', [])
    metadata = events_data.get('metadata', {})
    
    print(f"✓ Loaded {len(events)} events from file")
    if metadata:
        print(f"  Source: {metadata.get('source', 'N/A')}")
        print(f"  Extracted at: {metadata.get('extracted_at', 'N/A')}")
    
    if not events:
        print("\nNo events to add to calendar.")
        return
    
    # Authenticate and get calendar service
    print("\nAuthenticating with Google Calendar...")
    service = authenticate_google_calendar()
    
    if service:
        print("✓ Authentication successful!")
        # Add events to calendar
        add_events_to_calendar(service, events_data)
        print("\n✓ Process completed!")
    else:
        print("\n✗ Failed to authenticate with Google Calendar")
        print("Please check your credentials.json file and try again.")

if __name__ == '__main__':
    main()

